### ISSUE TITLE
Asynchronous processing that triggers an error message

### ISSUE THREAD

**Issue by phax** [phax/ph-as4#4]
Assume a two-way "push push" message wants to do the first push with an "ErrorMessage".
Does the second "push" need a "UserMessage" or can a signal message be pushed?

**Comment by phax** [comment]
HttpRequest1 -> UserMsg
HttpResponse1 -> ErrorMessage
-> second leg never executed

HttpRequest1 -> UserMsg
HttpResponse1 -> Receipt

HttpRequest2 -> UserMsg
HttpResponse2 -> ErrorMsg

**Comment by phax** [comment]
Rewrite: For two-way messaging I have the following flow of messages:
REQ1 + RESP1 -> REQ2 + RESP2

The above example handles ErrorMessages in RESP1 and RESP2.
But what if want to send an error message in REQ2 because some processing between RESP1 and REQ2 lead to an error condition?

**Comment by sfieten** [comment]
Hi Philip,
an error that occurs in the processing between RESP1 and REQ2 will be a business error, as the AS4 processing has finished after RESP1. So REQ2 would be a AS4 User Message that contains the business error as payload.
