### ISSUE TITLE
Travis indeterministically hangs

### ISSUE THREAD

**Issue by axan94** [phax/ph-as4#8]
Sometimes the Travis build process is killed for uncertain reasons.
Example report: https://travis-ci.org/phax/ph-as4/builds/256001865?utm_source=github_status&utm_medium=notification

![as4-1](https://user-images.githubusercontent.com/8873022/28517765-d939ea16-7065-11e7-9c98-86128a1ef215.PNG)
![as4-2](https://user-images.githubusercontent.com/8873022/28517768-da5972ea-7065-11e7-902e-355f6f5e6bdc.PNG)

**Comment by axan94** [comment]
Commit 2ef0eba rebuilt 8x times, everytime it was built correctly. It seems deactivating fork in the surefire-plugin does the trick. Still keeping this issue open to monitor this issue.

**Comment by phax** [comment]
Works now. Was a setup error.
