### ISSUE TITLE
Class AS4Handler won't compile

### ISSUE THREAD

**Issue by amckeown** [phax/ph-as4#9]
Hello Phillip

I downloaded the latest source code of ph-as4.   The class AS4Handler won't compile in using IBM JDK 1.8.   I get  Type mismatch: cannot convert from element type Object to Header  on line 189

![image](https://user-images.githubusercontent.com/43479310/48585166-c7b79c80-e8f9-11e8-8892-8f82abc864b1.png)

**Comment by phax** [comment]
@amckeown Can you please check what version of javax-mail is included in your dependencies? The latest version uses 1.6.2 which does contain the correct type:
![grafik](https://user-images.githubusercontent.com/196219/48693806-eb6d3200-ebda-11e8-8216-a58cfb00131d.png)

**Comment by amckeown** [comment]
Hi Philip
  Thank you for your assistance.    I had a older javax-mail jar file in the class path.
  Sincerly
  Andrew McKeown
  
   ---------- Original Message ----------
   From: Philip Helger <notifications@github.com>
   Date: November 19, 2018 at 3:10 AM
   
   
   @amckeown Can you please check what version of javax-mail is included in your dependencies? The latest version uses 1.6.2 which does contain the correct type:
